### ISSUE TITLE
Drone Type and Drone Model Selection in React App is Non-functional

### ISSUE THREAD

**Issue by mohamdlog** [oss-slu/DroneWorld#103]
**Description:**
In the React app, selecting a drone type or drone model does not work. Currently, the development of this functionality is still in progress. This parent issue will track the overall progress of enabling the ability for users to select a drone type and model, integrating both the front-end and back-end components to ensure proper functionality and communication between the simulator and the API.

**Sub-Issues:**
- [ ] https://github.com/oss-slu/DroneWorld/issues/14
- [ ] https://github.com/oss-slu/DroneWorld/issues/29
- [ ] https://github.com/oss-slu/DroneWorld/issues/32
- [ ] <>
