### ISSUE TITLE
Add Report Retrieval to Google Drive Storage Service

### ISSUE THREAD

**Issue by mohamdlog** [oss-slu/DroneWorld#174]
**Objective:**
Enable the `GoogleDriveStorageService` to list and retrieve reports, ensuring it matches GCS functionality and that the frontend displays the data the same way for both services.

**Tasks:**
- [x] **1. Update GoogleDriveStorageService:**
    - [x] Add methods to list and retrieve reports, similar to those in hardcoded in `simulation_server.py`(e.g., `list_reports()`, `get_report_content()`).
    - [x] Use Google Drive's API to handle folder navigation and file retrieval.
- [ ] **2. Testing:**
    - [x] Temporarily set up the simulation server to use `GoogleDriveStorageService` for report retrieval.
    - [ ] Verify that the data returned matches GCS formatting and works seamlessly with existing frontend displays.
    - [ ] Test edge cases such nested folder and empty folders.

**Files to Look at for More Information:**
- `DroneWorld\backend\PythonClient\multirotor\storage\gd_storage_service.py`
- `DroneWorld\backend\PythonClient\server\simulation_server.py`
